name: Auto build

on:
  #schedule:
  #  - cron: '0 * * * *' # every 1 hour
  push:
    branches:
      - develop
    tags-ignore:
      - '**'

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get existing docker tags
        id: docker-tags
        run: echo "::set-output name=dir::$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/tarampampam/hugo/tags?page_size=1024' | jq -r '."results"[]["name"]')"

      - name: Echo docker tags
        run: echo ${{ steps.docker-tags.outputs }}
