name: Build latest image

on:
  schedule: # Always runs on a default branch, docs: <https://git.io/Je5Z7>
    - cron: '0 0 * * *' # every 1 day
  push:
    branches: [develop] # change branch name if you want
    tags-ignore: ['**']

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      HUB_REPO: 'tarampampam/hugo'
      APP_REPO: 'gohugoio/hugo'
      APP_MAJOR_VERSION: '0.'
    steps:
      - name: Get releases info
        id: info
        run: |
          git_tags=$(curl -L -s "https://api.github.com/repos/${APP_REPO}/releases" |\
            jq -r '.[] | select(.tag_name | startswith("v'"${APP_MAJOR_VERSION}"'")) | .tag_name | sub("^v"; "")' |\
            tr '\n' ' ' | sed -e 's/[[:space:]]*$//')
          target=$(echo "$git_tags" | tr ' ' '\n' | sort -V -r | head -n 1)
          echo -e "App git tags:\t${git_tags}\nTarget version:\t${target}"
          echo "::set-output name=target::$target"

      - name: Check out code
        if: startsWith(steps.info.outputs.target, env.APP_MAJOR_VERSION) # Validate major version value
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build docker image
        if: startsWith(steps.info.outputs.target, env.APP_MAJOR_VERSION)
        env:
          TARGET_IMAGE: "${{ env.HUB_REPO }}:latest"
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null
          docker pull "${TARGET_IMAGE}" || true
          docker build \
            --build-arg "HUGO_VERSION=${{ steps.info.outputs.target }}" \
            --build-arg "BUILD_DATE=UNSET" \
            --cache-from "${TARGET_IMAGE}" \
            --tag "${TARGET_IMAGE}" \
            -f ./Dockerfile .
          docker push "${TARGET_IMAGE}"
