name: Test building

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    env:
      DOCKER_HUB_REPO: 'tarampampam/hugo'
      HUGO_GITHUB: 'gohugoio/hugo'
    steps:
      - name: Get releases info
        id: info
        run: |
          git_tags=$(curl -L -s "https://api.github.com/repos/${HUGO_GITHUB}/releases" |\
            jq -r '.[] | select(.tag_name) | .tag_name | sub("^v"; "")' |\
            tr '\n' ' ' | sed -e 's/[[:space:]]*$//')
          target=$(echo "$git_tags" | tr ' ' '\n' | sort -V -r | head -n 1)
          echo -e "App git tags:\t${git_tags}\nTarget version:\t${target}"
          echo "::set-output name=target::$target"

      - name: Check out code
        if: steps.info.outputs.target != ''
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build docker image
        if: steps.info.outputs.target != ''
        env:
          TARGET_IMAGE: "${{ env.DOCKER_HUB_REPO }}:latest"
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null
          docker build \
            --build-arg "HUGO_VERSION=${{ steps.info.outputs.target }}" \
            --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --tag "${TARGET_IMAGE}" \
            -f ./Dockerfile .
          docker push "${TARGET_IMAGE}"
